name: Deploy Forge App

on:
  push:
    branches:
      - master

env:
  HOME: /home/runner

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Forge credentials
        run: |
          mkdir -p ~/.forge
          echo "${{ secrets.FORGE_CREDENTIALS_BASE64 }}" | base64 --decode > ~/.forge/credentials
          cat ~/.forge/credentials  # Debug: remove after confirming
        shell: bash

      - name: Disable Forge analytics
        run: forge settings set usage-analytics false
        env:
          FORGE_DISABLE_KEYCHAIN: true

      - name: Check Forge login
        run: forge whoami
        env:
          FORGE_DISABLE_KEYCHAIN: true

      - name: Deploy Forge app
        run: forge deploy --non-interactive
        env:
          FORGE_DISABLE_KEYCHAIN: true
          FORGE_AUTO_CONFIRM: true