name: Deploy Forge App to Jira

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Forge CLI
        run: npm install -g @forge/cli

      - name: Authenticate with Forge
        env:
          FORGE_AUTO_CONFIRM: true
          FORGE_DISABLE_ANALYTICS: true
          FORGE_API_TOKEN: true
          FORGE_EMAIL: true
        run: forge login --token "${{ secrets.FORGE_API_TOKEN }}" --email "${{ secrets.FORGE_EMAIL }}"

      - name: Deploy Forge App
        run: forge deploy --non-interactive
