name: Deploy Forge App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Forge CLI
        run: npm install -g @forge/cli

      - name: Set Forge analytics preference
        run: forge settings set usage-analytics false
        env:
          FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
          FORGE_DISABLE_KEYCHAIN: true

      - name: Deploy Forge app
        run: forge deploy --non-interactive
        env:
          FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
          FORGE_DISABLE_KEYCHAIN: true
          FORGE_AUTO_CONFIRM: true
